export const repos = [
  {name:'student-evidence-commercial',category:'EDU Apps Plus — Commercial',visibility:'private',live:'https://student-evidence.eduappsplus.com.au'},
  {name:'pracpath-mentor-pst',category:'EDU Apps Plus — Commercial',visibility:'private',live:'https://pracpath.eduappsplus.com.au'},
  {name:'kofta-delights',category:'EDU Apps Plus — Commercial',visibility:'private'},
  {name:'small-job-tracker',category:'EDU Apps Plus — Commercial',visibility:'private'},
  {name:'friends-hot-50',category:'EDU Apps Plus — Commercial',visibility:'public',live:'https://hot50.eduappsplus.com.au'},
  {name:'fishfinder-helper',category:'EDU Apps Plus — Commercial',visibility:'private',live:'https://fishfinder-helper.vercel.app'},
  {name:'eduappsplus_website',category:'EDU Apps Plus — Business',visibility:'public',live:'https://www.eduappsplus.com.au'},
  {name:'EDU_market_analysis',category:'EDU Apps Plus — Business',visibility:'private'},
  {name:'elliart-murals',category:'Client / Business',visibility:'private'},
  {name:'nrpc_website2',category:'Client / Business',visibility:'public'},
  {name:'nrpc_website-2',category:'Client / Business',visibility:'public'},
  {name:'Theresaspeach',category:'Client / Business',visibility:'private'},
  {name:'year9-digital-semester-guide',category:'Teaching — Digital Technologies',visibility:'public',live:'https://year9-digital.eduappsplus.com.au'},
  {name:'y9-robotic-fingers-guide-app',category:'Teaching — Digital Technologies',visibility:'public'},
  {name:'y10-digital-tech-guide-app',category:'Teaching — Digital Technologies',visibility:'public'},
  {name:'digital_solutionsIA123_2027',category:'Teaching — Digital Technologies',visibility:'private'},
  {name:'edai-web-digital-solutions-coach',category:'Teaching — Digital Technologies',visibility:'public'},
  {name:'edai-web-11digital-solutions-coachT1',category:'Teaching — Digital Technologies',visibility:'private'},
  {name:'edai-web-digitech-ai-scaffold',category:'Teaching — Digital Technologies',visibility:'public'},
  {name:'edai-web-binary-learning-tool',category:'Teaching — Digital Technologies',visibility:'public'},
  {name:'edai-web-Y7_Digital_Tech_AI_workbook',category:'Teaching — Digital Technologies',visibility:'private'},
  {name:'edai-web-Y7_Digital_Impacts_AI_workbook',category:'Teaching — Digital Technologies',visibility:'private'},
  {name:'api-swiftui-explorer-ipad',category:'Teaching — Digital Technologies',visibility:'public'},
  {name:'fusion360_y9_app',category:'Teaching — Digital Technologies',visibility:'public'},
  {name:'ai-lab',category:'Teaching — AI',visibility:'public'},
  {name:'ai-classroom-studio-standalone',category:'Teaching — AI',visibility:'private'},
  {name:'ai-coding-coach',category:'Teaching — AI',visibility:'private'},
  {name:'aipersonaltutor',category:'Teaching — AI',visibility:'public'},
  {name:'edai-web-curriculum-ai-assistant',category:'Teaching — AI',visibility:'private'},
  {name:'edai-ios-content-study-app',category:'Teaching — Study / Student',visibility:'private'},
  {name:'StudyTrack-Lite',category:'Teaching — Study / Student',visibility:'public'},
  {name:'student_study_planner',category:'Teaching — Study / Student',visibility:'public'},
  {name:'student_study_planner_New',category:'Teaching — Study / Student',visibility:'public'},
  {name:'universalexamtrainer',category:'Teaching — Study / Student',visibility:'private'},
  {name:'y7exampractice',category:'Teaching — Study / Student',visibility:'private'},
  {name:'y7exampractice-next',category:'Teaching — Study / Student',visibility:'private'},
  {name:'y7buspartb',category:'Teaching — Business',visibility:'private'},
  {name:'edai-web-7Business-ai-student-teacher-support',category:'Teaching — Business',visibility:'public'},
  {name:'11CS2026',category:'Teaching — Curriculum / Planning',visibility:'private'},
  {name:'11CS_TLAP',category:'Teaching — Curriculum / Planning',visibility:'private'},
  {name:'QCAAEndorcement',category:'Teaching — Curriculum / Planning',visibility:'private'},
  {name:'qcaaendorsement',category:'Teaching — Curriculum / Planning',visibility:'private'},
  {name:'year7-be-guidance',category:'Teaching — Curriculum / Planning',visibility:'private'},
  {name:'school-excursion-reporter',category:'Teaching — School Operations',visibility:'public'},
  {name:'blueslip',category:'Teaching — School Operations',visibility:'private'},
  {name:'edai-ios-teacher-diary',category:'Teaching — School Operations',visibility:'public'},
  {name:'edai-ios-PC-hub-app',category:'Teaching — School Operations',visibility:'public'},
  {name:'peacewise-web',category:'Teaching — School Operations',visibility:'private'},
  {name:'christian-studies-leadership-app',category:'Christian / Ministry',visibility:'private'},
  {name:'christian-jam-time',category:'Christian / Ministry',visibility:'public'},
  {name:'salvation-trainer',category:'Christian / Ministry',visibility:'public'},
  {name:'religion-investigation',category:'Christian / Ministry',visibility:'private'},
  {name:'BibleAppV3',category:'Christian / Ministry',visibility:'private'},
  {name:'lastdaysv1',category:'Christian / Ministry',visibility:'public'},
  {name:'lastdayappv1',category:'Christian / Ministry',visibility:'private'},
  {name:'oldsongbook',category:'Music',visibility:'private'},
  {name:'songbook-vercel',category:'Music',visibility:'private'},
  {name:'songbookV2',category:'Music',visibility:'private'},
  {name:'SongJSONBuilder',category:'Music',visibility:'private'},
  {name:'Healthapp',category:'Personal / Lifestyle',visibility:'private'},
  {name:'MeasureApp',category:'Personal / Lifestyle',visibility:'private'},
  {name:'CarTracker',category:'Personal / Lifestyle',visibility:'private'},
  {name:'FishingWatchApp',category:'Personal / Lifestyle',visibility:'private'},
  {name:'TELWatch',category:'Personal / Lifestyle',visibility:'public'},
  {name:'TELhealthwatch',category:'Personal / Lifestyle',visibility:'public'},
  {name:'TELTravelApp',category:'Personal / Travel',visibility:'public'},
  {name:'phototravelapp',category:'Personal / Travel',visibility:'public'},
  {name:'grandadassistapp',category:'Personal / Lifestyle',visibility:'private'},
  {name:'essentials-tracker',category:'Personal / Productivity',visibility:'private'},
  {name:'minutewise-cloud',category:'Personal / Productivity',visibility:'private'},
  {name:'focuslockstarter',category:'Personal / Productivity',visibility:'public'},
  {name:'VideoCreationapp',category:'Creative Tools',visibility:'private'},
  {name:'chess_club',category:'Clubs / Community',visibility:'public'},
  {name:'farting-bin-stem',category:'Experiments / STEM',visibility:'public'},
  {name:'boat',category:'Experiments / Misc',visibility:'public'},
  {name:'speedresearchapp',category:'Experiments / Research',visibility:'private'},
  {name:'OpsAnchor',category:'Prototypes / Platforms',visibility:'private'},
  {name:'opsanchor-pro',category:'Prototypes / Platforms',visibility:'private'},
  {name:'startup-control-centre-prototype',category:'Prototypes / Platforms',visibility:'public'},
  {name:'startup-control-centre',category:'Prototypes / Platforms',visibility:'private'},
  {name:'digital-teaching-studio',category:'Prototypes / Platforms',visibility:'public'},
  {name:'AuthenticSupport',category:'Prototypes / Platforms',visibility:'public'},
  {name:'AppWebSite',category:'Meta / Portfolio',visibility:'public'},
  {name:'docs',category:'Meta / Portfolio',visibility:'public'},
  {name:'eduappsplus-site',category:'Meta / Portfolio',visibility:'public'},
  {name:'edai-portfolio-hub',category:'Meta / Portfolio',visibility:'public'},
  {name:'NodeStart',category:'Developer Tools',visibility:'public'},
  {name:'mac-kiosk-deployment-kit',category:'Developer Tools',visibility:'public'},
  {name:'student-evidence-app',category:'Older / Superseded',visibility:'private'},
  {name:'student-evidence-site',category:'Older / Superseded',visibility:'public'}
].map(r => ({...r, repoUrl:`https://github.com/trevore777/${r.name}`}));

export const categories = ['All', ...Array.from(new Set(repos.map(r => r.category))).sort()];
